name: C CI Build and Deploy


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          version: 1.0

      - name: Install jq and awk
        run: |
           sudo apt-get install -y jq
           sudo apt-get install -y gawk
           
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Build
        run: |
          scons
 
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak

      - name: Build Flatpak
        run: |
          cd glosungCI-CD
          flatpak-builder --force-clean flatpak-repo org.example.glosung.json
          flatpak build-bundle flatpak-repo glosung.flatpak org.example.glosung

      - name: Publish Flatpak
        uses: actions/upload-artifact@v2
        with:
          name: glosung-flatpak
          path: glosung.flatpak
          