name: C CI Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          version: 1.0

      - name: Install jq and awk
        run: |
           sudo apt-get install -y jq
           sudo apt-get install -y gawk
           
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons debhelper intltool libgtk-4-dev libadwaita-1-dev libxml2-dev libcurl4-gnutls-dev libgconf2-dev gettext
          sudo apt-get install -y python3-pip
          pip install opencv-contrib-python
          pip install opencv-python
          pip install -U Flask

      - name: Build
        run: |
          scons

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Flatpak Dependencies
        run: |
          sudo apt remove flatpak  
          sudo apt install flatpak
          sudo apt upgrade
          sudo apt update
          sudo apt-get install flatpak flatpak-builder -y
          sudo apt-get update -qy
          sudo apt-get install -y flatpak-builder flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.gnome.Platform/x86_64/40
          sudo flatpak update -y
          sudo flatpak install -y flathub org.freedesktop.Platform.GL.default//23.08
          sudo flatpak install flathub org.gnome.Platform/x86_64/3.38 -y
          git config --global user.name "glosung"
          git config --global user.email "nued_a@yahoo.com"
          git config --global init.defaultBranch main
          git config --global credential.helper 'cache --timeout=3600'
          git config --global init.defaultBranch main
          git config --global http.extraheader "AUTHORIZATION: basic ${{ secrets.TOKEN }}"
          echo -e "machine github.com\n  login ${{ secrets.TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc


      - name: Install Flatpak SDK and Platform
        run: |
          sudo flatpak-builder --force-clean --install-deps-from=flathub build-directory org.gnome.zbrown.glosung.json
          sudo flatpak-builder --force-clean --repo=repo-directory flatpak-build-directory org.gnome.zbrown.glosung.json


      - name: Build Flatpak Package
        run: |
          flatpak-builder --user --install --force-clean build-dir org.glosung.glosungci-cd.json
