name: Build and publish Flatpak package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flatpak-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder

      - name: Build Flatpak package
        run: |
          flatpak-builder --sdk --no-x11 build MyApp.flatpak

      - name: Publish Flatpak package
        run: |
          flatpak-builder --sdk --no-x11 publish MyApp.flatpak
